apiVersion: v1
kind: Pod
metadata:
  name: hostpath
spec:
  containers:
    - image: ubuntu
      name: ubuntu-container
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      volumeMounts:
        - mountPath: /app/src/dir
          name: hostvol
  volumes:
    - name: hostvol
      hostPath:
        path: /dir
        type: DirectoryOrCreate
