apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: empty-dir-ingress
spec:
  rules:
    - host: emptydir.example.com
      http:
        paths:
          - path: /write
            pathType: Prefix
            backend:
              service:
                name: emptydir-service
                port:
                  number: 3000
